import os
import subprocess
import json
import shutil
import re
import pandas as pd
from jinja2 import Template
import argparse

# ================= 配置区域 =================

# 1. flatc 编译器路径
FLATC_PATH = "./flatc.exe"

# 2. 输入 Excel 文件夹
EXCEL_DIR = "./Excels/gaobao"

# 3. 中间文件输出目录
TEMP_DIR = "./Temp"

# 4. C# 代码输出目录
OUTPUT_CODE_DIR = "./Generated/Configs"

# 5. 二进制数据输出目录
OUTPUT_DATA_DIR = "./ConfigDatas"

# 6. 命名空间
NAMESPACE = "Game.Config"

# 类型映射
TYPE_MAPPING = {
    "int": "int",
    "str": "string",
    "float": "float",
    "bool": "bool"
}

# ================= FBS 模板 =================
FBS_TEMPLATE = """
namespace {{ namespace }};

table {{ table_name }}Row {
{% for field in fields %}
  {% if field.is_array %}
  {{ field.name }}:[{{ field.type }}];
  {% else %}
  {{ field.name }}:{{ field.type }}{% if field.is_key %} (key){% endif %};
  {% endif %}
{% endfor %}
}

table {{ table_name }} {
  data:[{{ table_name }}Row];
}

root_type {{ table_name }};
"""

# ================= ConfigBinder 模板 (新增) =================
BINDER_TEMPLATE = """// <auto-generated>
//  Automatically generated by main.py. Do not modify.
// </auto-generated>

using Game.Config; 
using Google.FlatBuffers;

namespace Game.Config
{
    public static class ConfigBinder
    {
        public static void BindAll(ConfigManager manager)
        {
{% for name in table_names %}
            manager.Register<{{ name }}>(bb => {{ name }}.GetRootAs{{ name }}(bb));
{% endfor %}
        }
    }
}
"""


# ================= 工具函数 =================

def ensure_dir(directory):
    if not os.path.exists(directory):
        os.makedirs(directory)


def to_pascal_case_filename(text):
    """文件名转大驼峰"""
    base = os.path.basename(text)
    base = os.path.splitext(base)[0]
    words = re.split(r'[_\-\s]+', base)
    pascal_words = []
    for word in words:
        if not word: continue
        new_word = word[:1].upper() + word[1:]
        pascal_words.append(new_word)
    return "Config" + "".join(pascal_words)


def clean_value(value, excel_type):
    if pd.isna(value):
        if excel_type in ["int", "float"]: return 0
        if excel_type == "bool": return False
        return ""
    try:
        if excel_type == "int": return int(float(value))
        if excel_type == "float": return float(value)
        if excel_type == "bool": return bool(value)
        if excel_type == "str":
            s = str(value)
            return s[:-2] if s.endswith(".0") else s
    except:
        print("设置失败转换为默认值: \"" + value + "\"-> " + "0")
        return 0 if excel_type == "int" else ""
    return value


def get_csharp_prop_name(raw_name):
    """snake_case -> PascalCase"""
    parts = re.split(r'[_\s]+', raw_name)
    pascal_parts = []
    for p in parts:
        if not p: continue
        pascal_parts.append(p[:1].upper() + p[1:])
    return "".join(pascal_parts)


def resolve_naming_conflicts(fields_list):
    """解决 Defense / AddDefense 冲突"""
    csharp_map = {}
    for f in fields_list:
        cname = get_csharp_prop_name(f['name'])
        csharp_map[cname] = f

    for cname, field in csharp_map.items():
        if cname.startswith("Add") and len(cname) > 3:
            stem = cname[3:]
            if stem in csharp_map:
                old_name = field['name']
                new_name = old_name + "_"
                print(f"  [Auto-Fix] 命名冲突: '{old_name}' -> '{new_name}' (避免与 {stem} 冲突)")
                field['name'] = new_name


def generate_binder(table_names):
    """生成 ConfigBinder.Generated.cs"""
    if not table_names: return

    print(f"\n[Binder] 正在生成 ConfigBinder，共 {len(table_names)} 个表...")

    template = Template(BINDER_TEMPLATE)
    content = template.render(table_names=table_names)

    file_path = os.path.join(OUTPUT_CODE_DIR, "ConfigBinder.Generated.cs")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"  -> 已生成: {file_path}")


def process_excel(file_path):
    filename = os.path.basename(file_path)
    table_name = to_pascal_case_filename(filename)

    print(f"[{filename}] -> Table: [{table_name}] 处理中...")

    try:
        df = pd.read_excel(file_path, header=None)
    except Exception as e:
        print(f"  [Error] 读取失败: {e}")
        return None  # 返回 None 表示失败

    if len(df) < 4:
        print("  [Skip] 行数不足")
        return None

    row_names = df.iloc[0]
    row_types = df.iloc[1]

    fields_list = []
    array_groups = {}
    id_col_name = None

    array_pattern = re.compile(r"^(.*)\[(\d+)\]$")

    for idx, (name, type_str) in enumerate(zip(row_names, row_types)):
        if pd.isna(name) or pd.isna(type_str): continue
        name = str(name).strip()
        if name.startswith("#"): continue
        raw_type = str(type_str).strip().lower()
        if raw_type not in TYPE_MAPPING: continue
        fbs_type = TYPE_MAPPING[raw_type]
        match = array_pattern.match(name)

        if match:
            raw_array_name = match.group(1).strip()
            array_idx = int(match.group(2))
            array_name = raw_array_name if raw_array_name else "Arr"
            if array_name not in array_groups:
                array_groups[array_name] = {
                    "name": array_name, "type": fbs_type, "excel_type": raw_type,
                    "is_array": True, "indices": {}
                }
            array_groups[array_name]["indices"][array_idx] = idx
        else:
            is_key = (name.lower() == "id")
            if is_key: id_col_name = name
            fields_list.append({
                "name": name, "type": fbs_type, "excel_type": raw_type,
                "col_idx": idx, "is_array": False, "is_key": is_key
            })

    for arr_name, group_info in array_groups.items():
        fields_list.append(group_info)

    if not fields_list: return None

    resolve_naming_conflicts(fields_list)

    # FBS
    template = Template(FBS_TEMPLATE)
    fbs_content = template.render(namespace=NAMESPACE, table_name=table_name, fields=fields_list)
    fbs_path = os.path.join(TEMP_DIR, f"{table_name}.fbs")
    with open(fbs_path, "w", encoding="utf-8") as f:
        f.write(fbs_content)

    # Data
    data_df = df.iloc[3:].copy()
    if id_col_name:
        try:
            temp_sort_col = pd.to_numeric(data_df.iloc[:, 0], errors='coerce')
            if temp_sort_col.notna().sum() > len(temp_sort_col) * 0.5:
                data_df["_sort"] = temp_sort_col
                data_df = data_df.sort_values(by="_sort").drop(columns=["_sort"])
            else:
                data_df = data_df.sort_values(by=data_df.columns[0])
        except:
            pass

    rows_list = []
    for _, row in data_df.iterrows():
        if row.isna().all(): continue
        row_dict = {}
        for field in fields_list:
            if field["is_array"]:
                indices_map = field["indices"]
                arr_values = []
                for array_idx in sorted(indices_map.keys()):
                    val = clean_value(row.iloc[indices_map[array_idx]], field["excel_type"])
                    arr_values.append(val)
                row_dict[field["name"]] = arr_values
            else:
                val = clean_value(row.iloc[field["col_idx"]], field["excel_type"])
                row_dict[field["name"]] = val
        rows_list.append(row_dict)

    json_path = os.path.join(TEMP_DIR, f"{table_name}.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump({"data": rows_list}, f, ensure_ascii=False, indent=2)

    cmd_cs = [FLATC_PATH, "--csharp", "--gen-onefile", "-o", OUTPUT_CODE_DIR, fbs_path]
    cmd_bin = [FLATC_PATH, "--binary", "-o", OUTPUT_DATA_DIR, fbs_path, json_path]

    try:
        subprocess.run(cmd_cs, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        subprocess.run(cmd_bin, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

        # Rename .bin -> .bytes
        src_bin = os.path.join(OUTPUT_DATA_DIR, f"{table_name}.bin")
        dst_bytes = os.path.join(OUTPUT_DATA_DIR, f"{table_name}.bytes")
        if os.path.exists(src_bin):
            if os.path.exists(dst_bytes): os.remove(dst_bytes)
            os.rename(src_bin, dst_bytes)
            print(f"  -> 成功 ({len(rows_list)}条)")
            return table_name  # === 返回类名表示成功 ===

    except subprocess.CalledProcessError as e:
        print(f"  [Error] flatc 编译失败: {e.stderr.decode('utf-8', errors='ignore')}")

    return None


def main():
    # 1. 创建解析器
    parser = argparse.ArgumentParser(description="Excel 转 FlatBuffers & C# 代码生成工具")

    # 2. 添加参数
    # -i 是短参数, --input 是长参数, help 是说明
    parser.add_argument("-fp", "--flatc_path", help="flatc.exe的路径", required=True)
    parser.add_argument("-ed", "--excel_dir", help="目标excel的路径", required=True)
    parser.add_argument("-td", "--temp_dir", help="中间文件存放路径", default="./Temp")
    parser.add_argument("-oc", "--code_output_dir", help="CSharp代码输出路径", required=True)
    parser.add_argument("-od", "--data_output_dir", help="二进制文件输出路径",required=True)

    # 3. 解析参数
    args = parser.parse_args()

    global FLATC_PATH, EXCEL_DIR, TEMP_DIR, OUTPUT_CODE_DIR, OUTPUT_DATA_DIR
    FLATC_PATH = args.flatc_path
    EXCEL_DIR = args.excel_dir
    TEMP_DIR = args.temp_dir
    OUTPUT_CODE_DIR = args.code_output_dir
    OUTPUT_DATA_DIR = args.data_output_dir

    # 检查 flatc
    if not os.path.exists(FLATC_PATH):
        # 尝试从系统路径找
        alt_path = shutil.which("flatc")
        if alt_path:
            FLATC_PATH = alt_path
        else:
            print(f"[Error] 找不到 flatc: {FLATC_PATH}")
            return



    ensure_dir(TEMP_DIR)
    ensure_dir(OUTPUT_CODE_DIR)
    ensure_dir(OUTPUT_DATA_DIR)

    if not os.path.exists(EXCEL_DIR):
        print(f"[Error] Excel 目录不存在: {EXCEL_DIR}")
        return

    files = [f for f in os.listdir(EXCEL_DIR) if f.endswith(".xls") and not f.startswith("~$")]
    if not files:
        print(f"在 {EXCEL_DIR} 中未找到 Excel 文件")
        return

    print("=== 开始处理 ===")

    # 收集成功的表名
    success_tables = []

    for f in files:
        table_name = process_excel(os.path.join(EXCEL_DIR, f))
        if table_name:
            success_tables.append(table_name)

    # 生成 Binder
    generate_binder(success_tables)

    print("\n=== 全部完成 ===")


if __name__ == "__main__":
    main()